### ISSUE TITLE
ReadTimeoutError

### ISSUE THREAD

**Issue by bhennigar** [elasticsearch/curator#252]
Curator will no longer run after successfully running nightly for a couple weeks. There has been no change to the system. No updates run. Ubuntu 14.04 64bit. ElasticSearch 1.4.2. 
```
#curator --debug --host localhost --port 9200 --timeout 900 delete --time-unit days --timestring '%Y%m%d%H' --older-than 10 --prefix bro- --suffix 00
Traceback (most recent call last):
  File "./curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==2.1.1', 'console_scripts', 'curator')()
  File "/var/www/Brownian/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/var/www/Brownian/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2582, in load_entry_point
    return ep.load()
  File "/var/www/Brownian/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2265, in load
    return self._load()
  File "/var/www/Brownian/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2268, in _load
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/var/www/Brownian/local/lib/python2.7/site-packages/curator/__init__.py", line 1, in <module>
    from .curator import *
  File "/var/www/Brownian/local/lib/python2.7/site-packages/curator/curator.py", line 7, in <module>
    import elasticsearch
  File "/var/www/Brownian/local/lib/python2.7/site-packages/elasticsearch/__init__.py", line 18, in <module>
    from .client import Elasticsearch
  File "/var/www/Brownian/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 5, in <module>
    from ..transport import Transport
  File "/var/www/Brownian/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 4, in <module>
    from .connection import Urllib3HttpConnection
  File "/var/www/Brownian/local/lib/python2.7/site-packages/elasticsearch/connection/__init__.py", line 3, in <module>
    from .http_urllib3 import Urllib3HttpConnection
  File "/var/www/Brownian/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 3, in <module>
    from urllib3.exceptions import ReadTimeoutError, SSLError as UrllibSSLError
ImportError: cannot import name ReadTimeoutError
```

**Comment by untergeek** [comment]
The ReadTimeoutError suggests you should increase the --timeout parameter. The default is 39 seconds. Try increasing that to 60 or 120. 

—Aaron

**Comment by bhennigar** [comment]
I have timeout set to 900. The error appears immediately after starting the command.

**Comment by untergeek** [comment]
Sorry, my phone wasn't a big enough screen to see everything at once.

On closer inspection, the `ReadTimeoutError` is actually an `ImportError`.  It can't import something necessary.  I'm not sure what changed on your system, but something had to have changed.  

In the `elasticsearch` python module, identified in your path as: `/var/www/Brownian/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py`, there's an import line:

```python
from urllib3.exceptions import ReadTimeoutError, SSLError as UrllibSSLError
```

It can't find the `ReadTimeoutError` module within the `urllib3.exceptions` .  That makes this error part of the `URLLib3` package which is not controlled by the `curator` installation, except being installed as a dependency of the `elasticsearch` module installation.

You could perhaps uninstall/reinstall the elasticsearch module to see if dependent modules get re-installed.  Chances are, however, you may need to uninstall/reinstall the `urllib3` python module with

```
pip uninstall urllib3
pip install urllib3
```

…and see what happens.

**Comment by bhennigar** [comment]
No luck... I reinstalled curator as well.  Not a huge deal to rebuild the server as it's mostly for testing. I just can't figure out what changed.  Thanks

**Comment by bhennigar** [comment]
Sorry to bug you again but I rebuilt my server using the same process as I always use (worked in the past) and I'm still getting the error.
Here's the output from the curator install
```
# pip install elasticsearch-curator                                                                             Downloading/unpacking elasticsearch-curator
  Downloading elasticsearch-curator-2.1.1.tar.gz
  Running setup.py (path:/var/www/Brownian/build/elasticsearch-curator/setup.py)                                                                              egg_info for package elasticsearch-curator

    warning: no files found matching 'CHANGELOG'
    warning: no previously-included files matching '__pycache__' found under dir                                                                             ectory '*'
    warning: no previously-included files matching '*.py[co]' found under direct                                                                             ory '*'
Downloading/unpacking elasticsearch>=1.0.0,<2.0.0 (from elasticsearch-curator)
  Downloading elasticsearch-1.3.0-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking urllib3>=1.8,<2.0 (from elasticsearch>=1.0.0,<2.0.0->elast                                                                             icsearch-curator)
  Downloading urllib3-1.10-py2-none-any.whl (75kB): 75kB downloaded
Installing collected packages: elasticsearch-curator, elasticsearch, urllib3
  Running setup.py install for elasticsearch-curator

    warning: no files found matching 'CHANGELOG'
    warning: no previously-included files matching '__pycache__' found under dir                                                                             ectory '*'
    warning: no previously-included files matching '*.py[co]' found under direct                                                                             ory '*'
    Installing curator script to /var/www/Brownian/bin
    Installing es_repo_mgr script to /var/www/Brownian/bin
Successfully installed elasticsearch-curator elasticsearch urllib3
Cleaning up...
```

**Comment by untergeek** [comment]
I'm doing a clean install on Ubuntu 14.04 64-bit as well.

```
buh@Elasticbox (12:05 PM) [~] » head -1 /etc/apt/sources.list
# deb cdrom:[Lubuntu 14.04 LTS _Trusty Tahr_ - Release amd64 (20140416.2)]/ trusty main multiverse restricted universe
buh@Elasticbox (12:05 PM) [~] » uname -a
Linux Elasticbox 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
buh@Elasticbox (12:05 PM) [~] » curator
curator: command not found
buh@Elasticbox (12:05 PM) [~] » sudo pip2 install elasticsearch-curator
Downloading/unpacking elasticsearch-curator
  Downloading elasticsearch-curator-2.1.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/elasticsearch-curator/setup.py) egg_info for package elasticsearch-curator

    warning: no files found matching 'CHANGELOG'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
Downloading/unpacking elasticsearch>=1.0.0,<2.0.0 (from elasticsearch-curator)
  Downloading elasticsearch-1.3.0-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking urllib3>=1.8,<2.0 (from elasticsearch>=1.0.0,<2.0.0->elasticsearch-curator)
  Downloading urllib3-1.10-py2-none-any.whl (75kB): 75kB downloaded
Installing collected packages: elasticsearch-curator, elasticsearch, urllib3
  Running setup.py install for elasticsearch-curator

    warning: no files found matching 'CHANGELOG'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    Installing curator script to /usr/local/bin
    Installing es_repo_mgr script to /usr/local/bin
Successfully installed elasticsearch-curator elasticsearch urllib3
Cleaning up...
buh@Elasticbox (12:06 PM) [~] » curator --debug --host localhost --port 9200 --timeout 900 delete --time-unit days --timestring '%Y%m%d%H' --older-than 10 --prefix bro- --suffix 00
2015-01-17 12:06:06,530 INFO                        root                   main:334  Job starting...
2015-01-17 12:06:06,530 DEBUG         urllib3.util.retry               from_int:155  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-01-17 12:06:06,530 INFO      urllib3.connectionpool              _new_conn:188  Starting new HTTP connection (1): localhost
2015-01-17 12:06:06,531 DEBUG     urllib3.connectionpool          _make_request:368  "GET / HTTP/1.1" 200 334
2015-01-17 12:06:06,531 INFO               elasticsearch    log_request_success:62   GET http://localhost:9200/ [status:200 request:0.001s]
2015-01-17 12:06:06,531 DEBUG              elasticsearch    log_request_success:64   > None
2015-01-17 12:06:06,531 DEBUG              elasticsearch    log_request_success:65   < {
  "status" : 200,
  "name" : "Elasticbox",
  "cluster_name" : "untergeek",
  "version" : {
    "number" : "1.4.2",
    "build_hash" : "927caff6f05403e936c20bf4529f144f0c89fd8c",
    "build_timestamp" : "2014-12-16T14:11:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}

2015-01-17 12:06:06,531 INFO         elasticsearch.trace    log_request_success:72   curl -XGET 'http://localhost:9200/?pretty' -d ''
2015-01-17 12:06:06,531 DEBUG        elasticsearch.trace    log_request_success:75   #[200] (0.001s)
#{
#  "cluster_name": "untergeek",
#  "name": "Elasticbox",
#  "status": 200,
#  "tagline": "You Know, for Search",
#  "version": {
#    "build_hash": "927caff6f05403e936c20bf4529f144f0c89fd8c",
#    "build_snapshot": false,
#    "build_timestamp": "2014-12-16T14:11:12Z",
#    "lucene_version": "4.10.2",
#    "number": "1.4.2"
#  }
#}
2015-01-17 12:06:06,531 DEBUG     curator.curator_script          check_version:228  Detected Elasticsearch version 1.4.2
2015-01-17 12:06:06,531 DEBUG                       root                   main:359  Matching indices with pattern: bro-%Y%m%d%H
2015-01-17 12:06:06,531 DEBUG                       root                   main:363  argdict = {'url_prefix': '', 'func': <function delete at 0x7f90aded05f0>, 'prefix': 'bro-', 'log_level': 'INFO', 'timestring': '%Y%m%d%H', 'dry_run': False, 'exclude_pattern': None, 'logformat': 'Default', 'auth': None, 'ssl': False, 'host': 'localhost', 'command': 'delete', 'time_unit': 'days', 'timeout': 900, 'debug': True, 'disk_space': None, 'log_file': None, 'master_only': False, 'port': 9200, 'older_than': 10, 'suffix': '00'}
2015-01-17 12:06:06,531 INFO                        root                 delete:1017 Deleting indices...
2015-01-17 12:06:06,531 DEBUG         urllib3.util.retry               from_int:155  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-01-17 12:06:06,536 DEBUG     urllib3.connectionpool          _make_request:368  "GET /*/_settings?expand_wildcards=open%2Cclosed HTTP/1.1" 200 12709
2015-01-17 12:06:06,536 INFO               elasticsearch    log_request_success:62   GET http://localhost:9200/*/_settings?expand_wildcards=open%2Cclosed [status:200 request:0.005s]
2015-01-17 12:06:06,537 DEBUG              elasticsearch    log_request_success:64   > None
...
...
...
2015-01-17 12:06:06,539 INFO             curator.curator                 delete:1026 Specified indices deleted.
2015-01-17 12:06:06,539 INFO      curator.curator_script                   main:366  Done in 0:00:00.019744.
```

I do not know what you're encountering, but it is not likely to be part of curator itself.

**Comment by magnusbaeck** [comment]
The ReadTimeoutError exception was introduced in [commit 2074577 of github.com/shazow/urllib3](https://github.com/shazow/urllib3/commit/2074577ecf4b074984d63dc0bebf26afc217711c) which ended up in 1.7.1 and all subsequent releases, including 1.10 that you're getting. Could you verify that there actually is a `class ReadTimeoutError` in your urllib3/exceptions.py? And if so, is that the file actually read by Python when running Curator (check with strace)?

**Comment by bhennigar** [comment]
```class ReadTimeoutError``` does exist in urllib3/exceptions.ph.  Checking with strace, it's reading requests/packages/urllib3/exceptions.py which does not contain ```class ReadTimeoutError```

**Comment by untergeek** [comment]
Fascinating.  I wonder what's going on with this.

**Comment by bhennigar** [comment]
I don't think it would matter as it was working a couple weeks ago but I'm using a python virtualenv. Curator was installed while in the virtualenv.

**Comment by bhennigar** [comment]
Solved the problem. As I was using python virtualenv, I had installed curator while I was in the virtualenv and therefore it was looking for files in that location. I uninstalled it from the virtualenv and installed to the whole system and it worked.  Hope that makes sense.. It was a problem with my deployment, not the product.
