### ISSUE TITLE
Curator crashes on KeyErrors

### ISSUE THREAD

**Issue by rtoma** [elasticsearch/curator#259]
We run curator 2.1.1 for some time and got 2 crashes like:
```
Traceback (most recent call last):
  File "/usr/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==2.1.1', 'console_scripts', 'curator')()
  File "/usr/lib/python2.6/site-packages/curator/curator_script.py", line 364, in main
    arguments.func(client, **argdict)
  File "/usr/lib/python2.6/site-packages/curator/curator.py", line 905, in bloom
    _op_loop(client, matching_indices, op=disable_bloom_filter, dry_run=dry_run, **kwargs)
  File "/usr/lib/python2.6/site-packages/curator/curator.py", line 746, in _op_loop
    skipped = op(client, item, **kwargs)
  File "/usr/lib/python2.6/site-packages/curator/curator.py", line 536, in disable_bloom_filter
    if index_closed(client, index_name): # Don't try to disable bloom filter on a closed index.  It will re-open them
  File "/usr/lib/python2.6/site-packages/curator/curator.py", line 149, in index_closed
    return index_metadata['metadata']['indices'][index_name]['state'] == 'close'
KeyError: u'logstash-xpr-log4json-2015.01.12'
```

Any ideas why?

**Comment by untergeek** [comment]
Can you provide the command-line that ran this, so I can attempt to replicate the scenario that caused the error?

At first glance, it appears that it's trying to perform an operation on an index that no longer exists.  Do you have curator running as a cron job?  Did the previous day's cron job finish before it ran again?

**Comment by rtoma** [comment]
```
$ fgrep xpr-log4json /usr/local/bin/curator.sh
/usr/bin/curator --loglevel WARNING --timeout 3600 --host 10.98.252.244 optimize --prefix logstash-xpr-log4json- --older-than 2
/usr/bin/curator --loglevel WARNING --timeout 3600 --host 10.98.252.244 delete --prefix logstash-xpr-log4json- --older-than 14
/usr/bin/curator --loglevel WARNING --timeout 3600 --host 10.98.252.244 bloom --prefix logstash-xpr-log4json- --older-than 1
```

Maybe its a race condition between the delete and bloom command? Maybe the delete is async and still underway when the bloom starts?

Last night, same cron, all went fine as did before last weekend. Supporting the race condition hypothesis.

**Comment by untergeek** [comment]
It's not a race condition occurring within curator.  If your cluster is really busy the cluster updates may not be fully propagated from the elected master to all of the other nodes.  In such a case, it is possible that the node curator is polling has an out-of-date cluster state, and it shows the index as being present when it has already been deleted.

One possible solution is to run curator on all nodes, but with the `--master-only` flag set.  This will force curator to only perform operations on the elected master, and it will start, but quietly exit on the non-elected master nodes.  If curator is only ever run against the elected master, this "race" condition cannot occur because the elected master will always have the most up-to-date cluster state.

**Comment by rtoma** [comment]
Great answer! We'll implement this.

**Comment by rk295** [comment]
Hi, I'm not sure if this is the problem. I have a single ES node and I get the same problem. If I delete the index shown in the error and re-run curator, then another later index causes the same problem. But curiously it isn't _every_ index that causes the error.

```
%> pip list |grep elastic
elasticsearch (1.2.0)
elasticsearch-curator (2.1.2)
%> python --version
Python 2.7.5
%> curator optimize --older-than 2
2015-02-02 10:02:45,831 INFO      Job starting...
2015-02-02 10:02:45,831 INFO      Default timeout of 30 seconds is too low for command OPTIMIZE.  Overriding to 21,600 seconds (6 hours).
2015-02-02 10:02:45,834 INFO      Optimizing indices...
2015-02-02 10:02:45,842 INFO      Skipping index logstash-2015.01.04: Already optimized.
2015-02-02 10:02:45,845 INFO      Skipping index logstash-2015.01.05: Already optimized.
2015-02-02 10:02:45,848 INFO      Skipping index logstash-2015.01.06: Already optimized.
2015-02-02 10:02:45,850 INFO      Skipping index logstash-2015.01.08: Already optimized.
2015-02-02 10:02:45,853 INFO      Skipping index logstash-2015.01.09: Already optimized.
2015-02-02 10:02:45,856 INFO      Skipping index logstash-2015.01.10: Already optimized.
2015-02-02 10:02:45,860 INFO      Skipping index logstash-2015.01.11: Already optimized.
2015-02-02 10:02:45,864 INFO      Skipping index logstash-2015.01.12: Already optimized.
Traceback (most recent call last):
  File "/usr/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==2.1.2', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/curator/curator_script.py", line 383, in main
    arguments.func(client, **argdict)
  File "/usr/lib/python2.7/site-packages/curator/curator.py", line 1086, in optimize
    _op_loop(client, matching_indices, op=optimize_index, dry_run=dry_run, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/curator.py", line 779, in _op_loop
    skipped = op(client, item, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/curator.py", line 637, in optimize_index
    shards, segmentcount = get_segmentcount(client, index_name)
  File "/usr/lib/python2.7/site-packages/curator/curator.py", line 266, in get_segmentcount
    shards = client.indices.segments(index=index_name)['indices'][index_name]['shards']
KeyError: u'logstash-2015.01.13'
%>
```

**Comment by untergeek** [comment]
@rk295 Thanks for helping to debug this.

I cannot duplicate this, so I'm not sure what's going on.  You could go through a process to test this same thing:

```
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import curator
>>> import elasticsearch
>>> client = elasticsearch.Elasticsearch(host="192.168.123.204")
>>> index_name = "logstash-2015.01.30"
>>> client.indices.segments(index=index_name)['indices'][index_name]['shards']
{u'1': [{u'segments': {u'_ev4': {u'search': True, u'num_docs': 2921899, u'deleted_docs': 0, u'generation': 19264, u'size_in_bytes': 261485794, u'compound': False, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 2053962}, u'_ev5': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19265, u'size_in_bytes': 6122, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}}, u'num_search_segments': 2, u'routing': {u'node': u'pREk39dmQCCYZvTWzHx_sg', u'state': u'STARTED', u'primary': True}, u'num_committed_segments': 2}, {u'segments': {u'_euk': {u'search': True, u'num_docs': 2921899, u'deleted_docs': 0, u'generation': 19244, u'size_in_bytes': 261460273, u'compound': False, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 2053954}, u'_eul': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19245, u'size_in_bytes': 6122, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}}, u'num_search_segments': 2, u'routing': {u'node': u'jVKQ2johRn6AZmGrkvXWXA', u'state': u'STARTED', u'primary': False}, u'num_committed_segments': 2}], u'0': [{u'segments': {u'_ev4': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19264, u'size_in_bytes': 5835, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}, u'_ev2': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19262, u'size_in_bytes': 6121, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}, u'_ev3': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19263, u'size_in_bytes': 5827, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}, u'_ev0': {u'search': True, u'num_docs': 2921117, u'deleted_docs': 0, u'generation': 19260, u'size_in_bytes': 261317239, u'compound': False, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 2057674}, u'_ev1': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19261, u'size_in_bytes': 6122, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}}, u'num_search_segments': 5, u'routing': {u'node': u'pREk39dmQCCYZvTWzHx_sg', u'state': u'STARTED', u'primary': False}, u'num_committed_segments': 5}, {u'segments': {u'_euq': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19250, u'size_in_bytes': 5835, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}, u'_eup': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19249, u'size_in_bytes': 5827, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}, u'_euo': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19248, u'size_in_bytes': 6121, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}, u'_eun': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19247, u'size_in_bytes': 6122, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}, u'_eum': {u'search': True, u'num_docs': 2921117, u'deleted_docs': 0, u'generation': 19246, u'size_in_bytes': 261364679, u'compound': False, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 2057170}}, u'num_search_segments': 5, u'routing': {u'node': u'jVKQ2johRn6AZmGrkvXWXA', u'state': u'STARTED', u'primary': True}, u'num_committed_segments': 5}], u'3': [{u'segments': {u'_euu': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19254, u'size_in_bytes': 5913, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}, u'_eut': {u'search': True, u'num_docs': 2921717, u'deleted_docs': 0, u'generation': 19253, u'size_in_bytes': 261563657, u'compound': False, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 2056682}}, u'num_search_segments': 2, u'routing': {u'node': u'pREk39dmQCCYZvTWzHx_sg', u'state': u'STARTED', u'primary': True}, u'num_committed_segments': 2}, {u'segments': {u'_euu': {u'search': True, u'num_docs': 1, u'deleted_docs': 0, u'generation': 19254, u'size_in_bytes': 5913, u'compound': True, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 19778}, u'_eut': {u'search': True, u'num_docs': 2921717, u'deleted_docs': 0, u'generation': 19253, u'size_in_bytes': 261529369, u'compound': False, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 2057210}}, u'num_search_segments': 2, u'routing': {u'node': u'jVKQ2johRn6AZmGrkvXWXA', u'state': u'STARTED', u'primary': False}, u'num_committed_segments': 2}], u'2': [{u'segments': {u'_ev6': {u'search': True, u'num_docs': 2921177, u'deleted_docs': 0, u'generation': 19266, u'size_in_bytes': 261469390, u'compound': False, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 2060394}}, u'num_search_segments': 1, u'routing': {u'node': u'pREk39dmQCCYZvTWzHx_sg', u'state': u'STARTED', u'primary': False}, u'num_committed_segments': 1}, {u'segments': {u'_eus': {u'search': True, u'num_docs': 2921177, u'deleted_docs': 0, u'generation': 19252, u'size_in_bytes': 261473201, u'compound': False, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 2059530}}, u'num_search_segments': 1, u'routing': {u'node': u'jVKQ2johRn6AZmGrkvXWXA', u'state': u'STARTED', u'primary': True}, u'num_committed_segments': 1}], u'4': [{u'segments': {u'_evb': {u'search': True, u'num_docs': 2921902, u'deleted_docs': 0, u'generation': 19271, u'size_in_bytes': 261494542, u'compound': False, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 2061994}}, u'num_search_segments': 1, u'routing': {u'node': u'pREk39dmQCCYZvTWzHx_sg', u'state': u'STARTED', u'primary': False}, u'num_committed_segments': 1}, {u'segments': {u'_euo': {u'search': True, u'num_docs': 2921902, u'deleted_docs': 0, u'generation': 19248, u'size_in_bytes': 261482203, u'compound': False, u'version': u'4.10.2', u'committed': True, u'memory_in_bytes': 2060682}}, u'num_search_segments': 1, u'routing': {u'node': u'jVKQ2johRn6AZmGrkvXWXA', u'state': u'STARTED', u'primary': True}, u'num_committed_segments': 1}]}
```

If it works standalone but not with curator, there is a strong possibility that curator is not getting results back properly from your node, hence the empty key.  How busy is your single node?

Also, your elasticsearch python module is a version behind.  I think the most recent is 1.3.0.  Also, which version of Elasticsearch are you running against?

**Comment by rk295** [comment]
Hi, thanks for the response. I'm running ES version 1.4.0, I've bumped by ES python module to 1.3.0, thanks for mentioning that I hadn't noticed a new version was out. It didn't solve it though :(

I've run the tests you suggested above, and the results are interesting,  as you can see for the 13th and 14th of Jan there are no indices, but for later days in the month, the 25th for example it all looks fine.

I've checked into my notes, and the 13th/14th was about the time Logstash had died and wasn't sending any data, which probably accounts for my empty indexes.

Am I right in thinking that checking if Indices is not empty would probably solve this?

```
%> python
Python 2.7.5 (default, Jun 17 2014, 18:11:42)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import curator
>>> import elasticsearch
>>> client = elasticsearch.Elasticsearch(host="127.0.0.1")
>>> index_name = "logstash-2015.01.13"
>>> client.indices.segments(index=index_name)
{u'indices': {}, u'_shards': {u'successful': 0, u'failed': 0, u'total': 10}}
>>> index_name = "logstash-2015.01.14"
>>> client.indices.segments(index=index_name)
{u'indices': {}, u'_shards': {u'successful': 0, u'failed': 0, u'total': 10}}
>>> index_name = "logstash-2015.01.25"
>>> client.indices.segments(index=index_name)
{u'indices': {u'logstash-2015.01.25':...... much stuff removed....
```

**Comment by untergeek** [comment]
This is a fascinating case, that's for sure.

This is beyond atypical.  You apparently have an index called `logstash-2015.01.14`, and Logstash thinks it has 10 shards (5 primary, +1 replica each), but exactly 0 of those were successful.   Even more confusing is that 0 of those are listed as failed as well.

Indeed, this can be worked around by checking to ensure that `indices` is not empty.  This is such a rare case that while I _can_ add a check for this and continue, I think it would be wiser to show an error that a strange, empty index exists.

I will file a bug for this.

**Comment by rk295** [comment]
:+1:  Ha, I always manage to break things in creative ways! Thanks again, I'll keep an eye out for the commit.

**Comment by untergeek** [comment]
@rk295 See the change in #265

**Comment by rk295** [comment]
Confirmed, this fixes the problem for me. Thanks.
