### ISSUE TITLE
Curator can't find curator elasticsearch, OSX10.10.2, python 2.7

### ISSUE THREAD

**Issue by MichaelErmer** [elasticsearch/curator#271]
Heres my full trace:
````
$ sudo pip2.7 install elasticsearch-curator
The directory '/Users/user/Library/Logs/pip' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/user/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/user/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Collecting elasticsearch-curator
  Downloading elasticsearch-curator-2.1.2.tar.gz
Collecting elasticsearch<2.0.0,>=1.0.0 (from elasticsearch-curator)
  Downloading elasticsearch-1.4.0-py2.py3-none-any.whl (56kB)
    100% |################################| 57kB 495kB/s 
Requirement already satisfied (use --upgrade to upgrade): urllib3<2.0,>=1.8 in /Library/Python/2.7/site-packages (from elasticsearch<2.0.0,>=1.0.0->elasticsearch-curator)
Installing collected packages: elasticsearch, elasticsearch-curator

  Running setup.py install for elasticsearch-curator
    Installing curator script to /usr/local/bin
    Installing es_repo_mgr script to /usr/local/bin
Successfully installed elasticsearch-1.4.0 elasticsearch-curator-2.1.2
$ curator
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: elasticsearch>=1.0.0,<2.0.0
```

**Comment by untergeek** [comment]
This is, unfortunately, all too common.  Some setups (notably anything CentOS) have a hard time with the entry_point.  For some odd reason, it's kind of hit or miss with OS X, as is evidenced by the following:

```
$ sudo pip install elasticsearch-curator
Password:
Downloading/unpacking elasticsearch-curator
  Downloading elasticsearch-curator-2.1.2.tar.gz
  Running setup.py (path:/private/tmp/pip_build_root/elasticsearch-curator/setup.py) egg_info for package elasticsearch-curator

    warning: no files found matching 'CHANGELOG'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
Requirement already satisfied (use --upgrade to upgrade): elasticsearch>=1.0.0,<2.0.0 in /Library/Python/2.7/site-packages (from elasticsearch-curator)
Installing collected packages: elasticsearch-curator
  Running setup.py install for elasticsearch-curator

    warning: no files found matching 'CHANGELOG'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    Installing curator script to /usr/local/bin
    Installing es_repo_mgr script to /usr/local/bin
Successfully installed elasticsearch-curator
Cleaning up...
$ /usr/local/bin/curator
usage: curator [-h] [-v] [--host HOST] [--url_prefix URL_PREFIX] [--port PORT]
               [--ssl] [--auth AUTH] [--timeout TIMEOUT] [--master-only] [-n]
               [-D] [--loglevel LOG_LEVEL] [--logfile LOG_FILE]
               [--logformat LOGFORMAT]

               {alias,allocation,bloom,close,delete,optimize,replicas,show,snapshot}
               ...
curator: error: too few arguments
```

```
$ uname -a
Darwin Aironaut.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
```

On OS X, I'm not sure if it's because I have the OS X dev tools in place, or because I've steadily upgraded in-place since OS X 10.8.  In any case, I don't have this problem, but others do, and I can't explain it.  

The workaround is to call the `curator_script.py` directly:

```
$ python /Library/Python/2.7/site-packages/curator/curator_script.py
```

You could also `sudo chmod +x /Library/Python/2.7/site-packages/curator/curator_script.py` and symlink it: `sudo ln -s /Library/Python/2.7/site-packages/curator/curator_script.py /usr/local/bin/curator_script.py`
